name: Run Gunpla-calendar-exporter

on:
  schedule:
    - cron: "0 15 19 * *" # 毎月15日の日本時間0時（UTCの前日15時）
    - cron: "0 15 24 * *" # 毎月25日の日本時間0時（UTCの前日15時）

env:
  GUNPLA_CALENDAR_EXPORTER_ROOT: ${{ github.workspace }}

jobs:
  build-and-run:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_POOL }}
          service_account: app-account@gunpla-calendar-exporter.iam.gserviceaccount.com
          project_id: gunpla-calendar-exporter
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Install Dependencies
        run: go mod tidy
      - name: Build and Run App
        run: |
          go build -v ./cmd/main.go
          ./main
        working-directory: ${{ github.workspace }}
