name: Run Gunpla-calendar-exporter

on:
  push:
    branches:
      - main

env:
  GUNPLA_CALENDAR_EXPORTER_ROOT: ${{ github.workspace }}

jobs:
  build-and-run:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/245726004524/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-ip-provider
          service_account: app-account@gunpla-calendar-exporter.iam.gserviceaccount.com
          project_id: gunpla-calendar-exporter
      - name: Remove GOOGLE_APPLICATION_CREDENTIALS
        run: unset GOOGLE_APPLICATION_CREDENTIALS
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Install Dependencies
        run: go mod tidy
      - name: Build and Run App
        run: |
          go build -v ./cmd/main.go
          ./main
        working-directory: ${{ github.workspace }}
