name: Run Gunpla-calendar-exporter

on:
  schedule:
    - cron: "0 15 14 * *" # 毎月15日の日本時間0時（UTCの前日15時）
    - cron: "0 15 25 * *" # 毎月26日の日本時間0時（UTCの前日15時）

env:
  GUNPLA_CALENDAR_EXPORTER_ROOT: ${{ github.workspace }}

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Install Dependencies
        run: go mod tidy
      - name: Build and Run App
        run: |
          go build -v ./cmd/main.go
          ./main -upload false
        working-directory: ${{ github.workspace }}
      - name: Upload ICS File
        uses: actions/upload-artifact@v4
        with:
          name: ics-file
          path: ${{ github.workspace }}/gen/*.ics
